import 'dart:async';
import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:web_socket_channel/web_socket_channel.dart';

void main()=>runApp(const App());
class App extends StatelessWidget{const App({super.key});@override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'MacroPad Remote',theme:ThemeData.dark(useMaterial3:true).copyWith(scaffoldBackgroundColor:const Color(0xff181a1c),cardColor:const Color(0xff202326),colorScheme:const ColorScheme.dark(primary:Color(0xff2589ff),surface:Color(0xff202326))),home:const ConnectPage());}

class ConnectPage extends StatefulWidget{const ConnectPage({super.key});@override State<ConnectPage> createState()=>_ConnectPageState();}
class _ConnectPageState extends State<ConnectPage>{final ip=TextEditingController(text:'192.168.1.100'),code=TextEditingController();void go(){if(ip.text.trim().isEmpty||code.text.trim().isEmpty)return;Navigator.push(context,MaterialPageRoute(builder:(_)=>RemotePage(url:'ws://${ip.text.trim()}:8765/ws?token=${code.text.trim()}')));}@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('MacroPad Remote')),body:Center(child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:520),child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.stretch,children:[const Icon(Icons.grid_view_rounded,size:72),const SizedBox(height:20),const Text('Подключение к ПК',style:TextStyle(fontSize:26,fontWeight:FontWeight.w600)),const SizedBox(height:22),TextField(controller:ip,decoration:const InputDecoration(labelText:'IP компьютера',border:OutlineInputBorder())),const SizedBox(height:12),TextField(controller:code,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Код подключения',border:OutlineInputBorder())),const SizedBox(height:18),FilledButton(onPressed:go,style:FilledButton.styleFrom(shape:const RoundedRectangleBorder()),child:const Padding(padding:EdgeInsets.all(14),child:Text('Подключиться')))])))));}

class RemotePage extends StatefulWidget{final String url;const RemotePage({super.key,required this.url});@override State<RemotePage> createState()=>_RemotePageState();}
class _RemotePageState extends State<RemotePage>{WebSocketChannel? ch;StreamSubscription? sub;Profile? profile;int tab=0;String status='Подключение...';
 @override void initState(){super.initState();connect();}
 Future<void> connect()async{try{final c=WebSocketChannel.connect(Uri.parse(widget.url));await c.ready;if(!mounted)return;setState((){ch=c;status='Подключено';});sub=c.stream.listen(onData,onError:(_){if(mounted)setState(()=>status='Ошибка');},onDone:(){if(mounted)setState(()=>status='Отключено');});}catch(_){if(mounted)setState(()=>status='Не удалось подключиться');}}
 void onData(dynamic m){try{final j=jsonDecode(m as String);if(j['type']=='profile'&&j['profile']!=null)setState(()=>profile=Profile.fromJson(j['profile']));}catch(_){}}
 void send(String h){if(h.isEmpty)return;ch?.sink.add(jsonEncode({'hotkey':h}));}
 @override void dispose(){sub?.cancel();ch?.sink.close();super.dispose();}
 @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:Text(profile?.name??'MacroPad Remote'),actions:[Padding(padding:const EdgeInsets.only(right:14),child:Center(child:Row(children:[Icon(Icons.circle,size:9,color:status=='Подключено'?Colors.green:Colors.grey),const SizedBox(width:7),Text(status)])))]),body:SafeArea(child:[deck(),touchpad(),keyboard(),media()][tab]),bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(i)=>setState(()=>tab=i),destinations:const[NavigationDestination(icon:Icon(Icons.grid_view),label:'Deck'),NavigationDestination(icon:Icon(Icons.touch_app),label:'Touchpad'),NavigationDestination(icon:Icon(Icons.keyboard),label:'Keyboard'),NavigationDestination(icon:Icon(Icons.play_circle),label:'Media')]));
 Widget deck(){final p=profile;if(p==null)return const Center(child:CircularProgressIndicator());return LayoutBuilder(builder:(c,b){final cols=p.columns.clamp(1,10).toInt();return GridView.builder(padding:const EdgeInsets.all(12),gridDelegate:SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:cols,crossAxisSpacing:7,mainAxisSpacing:7,childAspectRatio:1.08),itemCount:p.tiles.length,itemBuilder:(c,i){final t=p.tiles[i];return Material(color:const Color(0xff24282c),shape:const RoundedRectangleBorder(side:BorderSide(color:Color(0xff3b4147))),child:InkWell(onTap:()=>send(t.hotkey),child:Padding(padding:const EdgeInsets.all(7),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(iconFor(t.title),size:30),const SizedBox(height:8),Text(t.title,textAlign:TextAlign.center,maxLines:2,overflow:TextOverflow.ellipsis)]))));});});}
 IconData iconFor(String s){final q=s.toLowerCase();if(q.contains('сохран'))return Icons.save_outlined;if(q.contains('скрин'))return Icons.crop_free;if(q.contains('брауз'))return Icons.public;if(q.contains('пап'))return Icons.folder_outlined;if(q.contains('восп'))return Icons.play_arrow;if(q.contains('звук'))return Icons.volume_off;if(q.contains('назад'))return Icons.arrow_back;return Icons.apps;}
 Widget touchpad()=>Padding(padding:const EdgeInsets.all(16),child:Column(children:[Expanded(child:Container(decoration:BoxDecoration(color:const Color(0xff202326),border:Border.all(color:const Color(0xff3b4147))),child:const Center(child:Text('Touchpad\nподдержка движения мыши будет подключена следующим шагом',textAlign:TextAlign.center,style:TextStyle(color:Colors.grey))))),const SizedBox(height:10),Row(children:[Expanded(child:OutlinedButton(onPressed:()=>send('ENTER'),child:const Text('Left'))),const SizedBox(width:8),Expanded(child:OutlinedButton(onPressed:()=>send('ESC'),child:const Text('Right')))])]));
 Widget keyboard()=>ListView(padding:const EdgeInsets.all(16),children:[const Text('Keyboard',style:TextStyle(fontSize:22,fontWeight:FontWeight.w600)),const SizedBox(height:14),Wrap(spacing:8,runSpacing:8,children:[key('Ctrl+C','CTRL+C'),key('Ctrl+V','CTRL+V'),key('Ctrl+Z','CTRL+Z'),key('Ctrl+S','CTRL+S'),key('Alt+Tab','ALT+TAB'),key('Win+D','WIN+D'),key('Enter','ENTER'),key('Esc','ESC'),key('←','LEFT'),key('↑','UP'),key('↓','DOWN'),key('→','RIGHT')])]);
 Widget key(String n,String h)=>SizedBox(width:105,height:62,child:OutlinedButton(onPressed:()=>send(h),style:OutlinedButton.styleFrom(shape:const RoundedRectangleBorder()),child:Text(n,textAlign:TextAlign.center)));
 Widget media()=>Center(child:Wrap(spacing:12,runSpacing:12,children:[IconButton.filledTonal(onPressed:()=>send('VOLUME_DOWN'),icon:const Icon(Icons.volume_down),iconSize:34),IconButton.filled(onPressed:()=>send('MEDIA_PLAY'),icon:const Icon(Icons.play_arrow),iconSize:38),IconButton.filledTonal(onPressed:()=>send('VOLUME_UP'),icon:const Icon(Icons.volume_up),iconSize:34),IconButton.filledTonal(onPressed:()=>send('VOLUME_MUTE'),icon:const Icon(Icons.volume_off),iconSize:34)]));}

class Profile{final String name;final int rows,columns;final List<Tile> tiles;Profile(this.name,this.rows,this.columns,this.tiles);factory Profile.fromJson(Map<String,dynamic>j)=>Profile(j['Name']??j['name']??'Profile',j['Rows']??j['rows']??3,j['Columns']??j['columns']??4,((j['Tiles']??j['tiles']??[])as List).map((x)=>Tile.fromJson(Map<String,dynamic>.from(x))).toList());}
class Tile{final String title,hotkey;Tile(this.title,this.hotkey);factory Tile.fromJson(Map<String,dynamic>j)=>Tile(j['Title']??j['title']??'Button',j['Hotkey']??j['hotkey']??'');}
