name: macropad_remote
description: MacroPad Remote phone and tablet companion
publish_to: 'none'
version: 1.0.0+40
environment:
  sdk: '>=3.8.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^3.0.3
  mobile_scanner: ^7.4.2
  universal_ble: ^2.3.0
  flutter_secure_storage: ^11.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
